In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("/content/advertising.csv")
df

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [3]:
X=df[['TV']]
y=df['Sales']

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X

        TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [6]:
y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ...
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=45)

In [8]:
len(X_train)

160

In [10]:
len(y_train)

160

In [9]:
len(X_test)

40

In [11]:
len(y_test)

40

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
reg=LinearRegression()

In [14]:
reg.fit(X_train,y_train)

LinearRegression()

In [15]:
training_results=reg.predict(X_train)
training_results

array([17.2800647 , 19.41361427,  9.20671314, 14.68566843, 22.51437297,
       14.67997896,  9.50825481, 10.77700562, 21.62681635, 10.65183738,
       23.12314578, 21.20010644, 20.8928753 , 18.52605765,  9.2124026 ,
       13.36002296, 14.69704736, 23.03211433, 18.90725184, 19.01535168,
       18.90156237, 18.68536268,  8.32484598, 11.03303157, 14.40119515,
       17.2800647 , 11.63611491, 12.20506146, 11.209405  , 12.87072893,
       14.25326905,  8.5524246 , 13.0072761 , 10.61770058, 19.41361427,
        8.3874301 , 19.29413549, 22.50299404, 18.53174711, 23.42468745,
       22.70212533, 18.00262682,  9.29205512, 22.73057266, 14.45240034,
       17.75229034, 20.26703409,  8.92223986, 11.10699462,  6.99351105,
       11.0102737 , 12.47246634, 19.07224634, 22.33231007, 22.89556716,
        9.60497572, 19.68670861,  7.77865729, 15.14082567, 21.03511194,
       17.78073766, 20.40927073, 19.50464571, 11.90351979, 13.0072761 ,
       20.42064966,  7.73883103, 18.0879688 , 19.73222434, 16.83059692,
       16.25027144,  7.72176264, 19.74929273, 23.62381875,  7.73883103,
        7.0674741 , 15.66994596, 13.59898051, 18.12779506,  8.18260934,
        7.86399927, 18.42364727,  6.80006922, 14.12241134, 11.72145689,
       18.12779506, 19.18603565,  7.23815807, 13.05848129, 10.6973531 ,
       20.10203959, 12.71142389, 16.57457098, 20.40358127,  7.25522646,
       11.78404101, 18.07658987, 11.32319431, 19.14620939, 18.7479468 ,
       11.05578943, 17.4450592 , 14.60601591,  9.80410701, 12.11971948,
       20.42064966, 17.45074866,  7.51125241, 23.24262456, 12.10265108,
        8.93361879, 20.51168111, 18.00262682, 12.23350879, 21.70646887,
       16.18199786, 12.60332405, 13.76397501, 13.61604891, 10.56649539,
        8.21674614, 18.97552542, 23.46451371,  7.50556295, 10.03168564,
       14.74256308, 13.42829655, 11.10130515, 13.18364953, 21.94542642,
       18.37244208,  7.17557395, 19.96549242,  7.20402128, 19.60705609,
       22.77039892,  8.11433576, 10.30477998, 16.83059692, 17.47919599,
       10.93631065, 19.19172511,  7.249537  , 11.86369353, 13.91190112,
       14.50929499, 17.14920699, 19.30551442, 10.68597417, 17.87745858,
       14.79945774,  7.82986248, 20.26703409, 16.06251908,  7.82417302,
       16.05114015, 12.29040344, 19.81756632, 21.84870551,  7.42591043])

In [17]:
X_train=X_train.to_numpy().ravel()

In [18]:
training_data=pd.DataFrame({"X_Train":X_train,
                            "y_train":y_train,
                            "y_pred":training_results})
training_data

     X_Train  y_train     y_pred
97     184.9     20.5  17.280065
174    222.4     16.5  19.413614
138     43.0      9.6   9.206713
67     139.3     13.4  14.685668
175    276.9     27.0  22.514373
..       ...      ...        ...
95     163.3     16.9  16.051140
32      97.2     13.2  12.290403
124    229.5     19.7  19.817566
131    265.2     17.7  21.848706
158     11.7      7.3   7.425910

[160 rows x 3 columns]

In [19]:
from sklearn.metrics import r2_score,root_mean_squared_error
print("Training Performance")
print("---------------------")
print(f"Accuracy of Training Data:{r2_score(X_train,training_results)}")
print(f"Loss of Training Data:{root_mean_squared_error(X_train,training_results)}")

Training Performance
---------------------
Accuracy of Training Data:-2.1210325355492716
Loss of Training Data:153.2628777421456